tap "1password/tap"
tap "atlassian/cloudtoken", "git@bitbucket.org:atlassian/cloudtoken-homebrew-tap.git"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "withgraphite/tap"
brew "coreutils"
brew "asdf"
brew "chezmoi"
brew "curl"
brew "git"
brew "maven"
brew "pyenv"
brew "ripgrep"
brew "yarn"
brew "withgraphite/tap/graphite"
cask "1password-cli"
cask "cloudtoken"
cask "font-fira-code"
