tap "1password/tap"
tap "atlassian/cloudtoken", "git@bitbucket.org:atlassian/cloudtoken-homebrew-tap.git"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "coreutils"
brew "asdf"
brew "chezmoi"
brew "curl"
brew "difftastic"
brew "exa"
brew "git"
brew "pnpm", link: false
brew "pyenv"
brew "ripgrep"
brew "tig"
brew "tldr"
brew "yarn"
brew "zsh"
cask "1password-cli"
cask "cloudtoken"
cask "font-fira-code"
cask "font-jetbrains-mono-nerd-font"
